gcc-env:
  compiler:
      - toolchain: gcc
        spec: gcc@11
  mpi:
      spec: cray-mpich
      gpu: cuda
  unify: true
  specs:
  - boost@1.76
  - cmake
  - cuda@11.8
  - python@3.10
  variants:
  - +mpi
  - +cuda
  - cuda_arch=80
  views:
    default:
